### ISSUE TITLE
Token is in the repo

### ISSUE THREAD

**Issue by hasanpasha** [nnko0o/Manga-Reader-Bot#1]
سلام عليكم, الـtoken هذا فعال!؟
https://github.com/nnko0o/Manga-Reader-Bot/blob/1c2ffc425372e2c664a384b9767322c252aec1bc/bot/PyrogramBot.py#L28
إذا فعال اقترح انك تمسحه من هنا وتحفظه في ملف `env` وتستدعي الـtoken من الملف..

**Comment by hasanpasha** [comment]
وطبعا إذا بغض النظر إذا فعال ام لا, الاحسن تلغي هذا التوكن .

**Comment by nnko0o** [comment]
وعليكم السلام ورحمة الله وبركاته,
أن شاء من افرغ احسن البوت كامل مو بس هذا الشيء , لغيت التوكن و 
API KEYs حالياً
